# Generated by Django 4.1 on 2023-03-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_entry_exercise_alter_entry_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
