# Generated by Django 4.1 on 2023-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_entry_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='hello', max_length=500, null=True),
        ),
    ]
