# Generated by Django 4.1 on 2023-04-01 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customer_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_created',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
